version: "3"

services:
  backend:
    restart: always
    build:
      dockerfile: Dockerfile.dev
      context: .
    environment:
      BACKEND_PORT: ${BACKEND_PORT}
    command: sh -c './wait-for postgres:${PG_PORT} -- yarn run start'
    ports:
      - ${BACKEND_PORT}:${BACKEND_PORT}
    volumes:
      - /app/node_modules
      - ./:/app
    depends_on:
      - postgres

  postgres:
    restart: always
    image: "postgres"
    environment:
      POSTGRES_USER: ${PG_USER}
      POSTGRES_PASSWORD: ${PG_PASSWORD}
      POSTGRES_DB: ${PG_DATABASE}
      PGPORT: ${PG_PORT}
    ports:
      - ${PG_PORT}:${PG_PORT}
    volumes:
      - ./pgData:/var/lib/postgresql/data
