version: "3"

services:
  backend:
    restart: always
    build:
      dockerfile: Dockerfile.dev
      context: .
    environment:
      BACKEND_PORT: "5001"
      PGHOST: "postgres"
      PGPORT: "5433"
      PGDATABASE: "postgres"
      PGUSER: "postgres"
      PGPASSWORD: "qwerty123"
    command: sh -c './wait-for postgres:5433 -- yarn run dev'
    volumes:
      - /app/node_modules
      - ./:/app
    depends_on:
      - postgres

  postgres:
    restart: always
    image: "postgres"
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "qwerty123"
      POSTGRES_DB: "postgres"
      PGPORT: "5433"
    ports:
      - "5433:5433"
    volumes:
      - ./pgData:/var/lib/postgresql/data
